# -------------------------------
# Project Information
# -------------------------------
sonar.projectKey=GraminDelivery
sonar.projectName=GraminDelivery
sonar.projectVersion=1.0

# -------------------------------
# SonarQube Server
# -------------------------------
sonar.host.url=http://localhost:9005
sonar.token=sqp_4e04ff7265c2aba6967f815a5d58efa17be1a152

# -------------------------------
# Source Code
# -------------------------------
sonar.sources=.

# -------------------------------
# Encoding
# -------------------------------
sonar.sourceEncoding=UTF-8

# -------------------------------
# Exclusions (VERY IMPORTANT)
# -------------------------------
sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/.next/**,\
**/.scannerwork/**,\
**/.git/**,\
**/coverage/**,\
**/*.log,\
**/*.lock,\
**/tmp/**,\
**/public/**,\
**/*.min.js,\
**/vendor/**

# -------------------------------
# Test Exclusions
# -------------------------------
sonar.test.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**

# -------------------------------
# JavaScript / TypeScript
# -------------------------------
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# -------------------------------
# Ignore environment files
# -------------------------------
sonar.coverage.exclusions=\
**/*.test.js,\
**/*.spec.js,\
**/*.config.js,\
**/.env,\
**/.env.*
